vim.api.nvim_set_hl(0, "Normal", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalFloat", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "FloatBorder", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "Pmenu", { ctermbg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", { fg = "#dbbc7f", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingError", { fg = "#e67e80", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", { fg = "LightGrey", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", { fg = "LightBlue", bg = "NONE" })
--vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = "#fcb103", bg = "NONE" })
--vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#fcb103", bg = "NONE" })
--vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#fcb103", bg = "NONE" })
--vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultWarning", { fg = "#fcb103", bg = "NONE" })
--vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineWarning", { fg = "#fcb103", bg = "NONE" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_normal", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_insert", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_visual", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_replace", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_command", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_terminal", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl(0, "lualine_b_diagnostics_warn_inactive", { fg = "#fcb103", bg = "#3F4758" })
--vim.api.nvim_set_hl('highlight! CmpItemAbbrDeprecated bg=NONE =strikethrough fg=#808080')
---- blue
--vim.api.nvim_set_hl('highlight! CmpItemAbbrMatch bg=NONE fg=#569CD6')
--vim.api.nvim_set_hl('highlight! CmpItemAbbrMatchFuzzy bg=NONE fg=#569CD6')
---- light blue
--vim.api.nvim_set_hl('highlight! CmpItemKindInterface bg=NONE fg=#9CDCFE')
---- pink
--vim.api.nvim_set_hl('highlight! CmpItemKindFunction bg=NONE fg=#C586C0')
--vim.api.nvim_set_hl('highlight! CmpItemKindMethod bg=NONE fg=#C586C0')
---- front
--vim.api.nvim_set_hl('highlight! CmpItemKindKeyword bg=NONE fg=#D4D4D4')
--vim.api.nvim_set_hl('highlight! CmpItemKindProperty bg=NONE fg=#D4D4D4')
--vim.api.nvim_set_hl('highlight! CmpItemKindUnit bg=NONE fg=#D4D4D4')
--vim.cmd("highlight! link CmpItemKind Pmenu guibg=NONE")
--vim.cmd("highlight! link CmpItemAbbr Pmenu guibg=NONE")
--vim.cmd("highlight! link CmpItemMenu Pmenu guibg=NONE")
--vim.(0, "CmpItemKindText", { bg = "NONE", fg = "#569CD6" })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { bg = "NONE", fg = "LightBlue" })
vim.api.nvim_set_hl(0, "CmpItemKindText", { bg = "NONE", fg = "LightBlue" })
vim.api.nvim_set_hl(0, "CmpItemKindValue", { bg = "NONE", fg = "LightBlue" })
vim.api.nvim_set_hl(0, "CmpItemKindInterface", { bg = "NONE", fg = "#569CD6" })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { bg = "NONE", fg = "#b286ce" })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { bg = "NONE", fg = "#b286ce" })
vim.api.nvim_set_hl(0, "CmpItemKindModule", { bg = "NONE", fg = "#b286ce" })
vim.api.nvim_set_hl(0, "CmpItemKindConstant", { bg = "NONE", fg = "White" })
vim.api.nvim_set_hl(0, "CmpItemKindEvent", { bg = "NONE", fg = "White" })
vim.api.nvim_set_hl(0, "CmpItemKindField", { bg = "NONE", fg = "White" })
--vim.api.nvim_set_hl(0, "CmpItemKindFile", { bg = "NONE", fg = "#aa84aa" })
--vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { bg = "NONE", fg = "#aa84aa" })
--vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { bg = "NONE", fg = "#aa84aa" })
--vim.api.nvim_set_hl(0, "CmpItemKindConstructor", { bg = "NONE", fg = "#aa84aa" })
--vim.api.nvim_set_hl(0, "CmpItemKindProperty", { bg = "NONE", fg = "#aa84aa" })
--vim.api.nvim_set_hl(0, "CmpItemKindStruct", { bg = "NONE", fg = "#aa84aa" })
